version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: pitch_backend_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pitch_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pitch_backend
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/pitch_backend?sslmode=disable
    depends_on:
      - postgres
    ports:
      - "8082:8080"

volumes:
  postgres-data:
