// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/pitchbackend/v1/hello.proto

package pitchbackendv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "pitch_backend/presentation/pb/api/pitchbackend/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HelloServiceName is the fully-qualified name of the HelloService service.
	HelloServiceName = "api.pitchbackend.v1.HelloService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HelloServiceGetHelloProcedure is the fully-qualified name of the HelloService's GetHello RPC.
	HelloServiceGetHelloProcedure = "/api.pitchbackend.v1.HelloService/GetHello"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	helloServiceServiceDescriptor        = v1.File_api_pitchbackend_v1_hello_proto.Services().ByName("HelloService")
	helloServiceGetHelloMethodDescriptor = helloServiceServiceDescriptor.Methods().ByName("GetHello")
)

// HelloServiceClient is a client for the api.pitchbackend.v1.HelloService service.
type HelloServiceClient interface {
	GetHello(context.Context, *connect.Request[v1.GetHelloRequest]) (*connect.Response[v1.GetHelloResponse], error)
}

// NewHelloServiceClient constructs a client for the api.pitchbackend.v1.HelloService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHelloServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HelloServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &helloServiceClient{
		getHello: connect.NewClient[v1.GetHelloRequest, v1.GetHelloResponse](
			httpClient,
			baseURL+HelloServiceGetHelloProcedure,
			connect.WithSchema(helloServiceGetHelloMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// helloServiceClient implements HelloServiceClient.
type helloServiceClient struct {
	getHello *connect.Client[v1.GetHelloRequest, v1.GetHelloResponse]
}

// GetHello calls api.pitchbackend.v1.HelloService.GetHello.
func (c *helloServiceClient) GetHello(ctx context.Context, req *connect.Request[v1.GetHelloRequest]) (*connect.Response[v1.GetHelloResponse], error) {
	return c.getHello.CallUnary(ctx, req)
}

// HelloServiceHandler is an implementation of the api.pitchbackend.v1.HelloService service.
type HelloServiceHandler interface {
	GetHello(context.Context, *connect.Request[v1.GetHelloRequest]) (*connect.Response[v1.GetHelloResponse], error)
}

// NewHelloServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHelloServiceHandler(svc HelloServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	helloServiceGetHelloHandler := connect.NewUnaryHandler(
		HelloServiceGetHelloProcedure,
		svc.GetHello,
		connect.WithSchema(helloServiceGetHelloMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.pitchbackend.v1.HelloService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HelloServiceGetHelloProcedure:
			helloServiceGetHelloHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHelloServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHelloServiceHandler struct{}

func (UnimplementedHelloServiceHandler) GetHello(context.Context, *connect.Request[v1.GetHelloRequest]) (*connect.Response[v1.GetHelloResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.pitchbackend.v1.HelloService.GetHello is not implemented"))
}
